language: go
script: "./gok.sh"
install:
    - export PATH="$HOME/gopath/bin:$PATH"
    - go get code.google.com/p/go.tools/cmd/vet
    - go get github.com/golang/lint/golint
    - go get -d -v ./... && go build -v ./...
